{{- if or .Values.binderhub.config.BinderHub.use_registry .Values.binderhub.config.BinderHub.buildImagePullConfig }}
kind: Secret
apiVersion: v1
metadata:
  name: jupyterhub-image-pull-config
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "buildImagePullConfig" . | b64enc | quote }}
{{- end }}
